### ISSUE TITLE
Updating the JLLs with Apple M1 support

### ISSUE THREAD

**Issue by fingolfin** [felipenoris/Mongoc.jl#86] opened 2021-10-21 20:04 UTC
It would be nice if the JLLs used by this package were available for Apple M1 (and possibly some of the other platforms being added in Julia 1.7).

I can help with updating the builders on Yggdrasil. However, this would be much simpler if I could only build them for Julia >= 1.6 (note that 1.6 is scheduled to become the new Julia LTS release once 1.7 is released). Right now, this package supports Julia down to 1.3... If that's important to you, one can certainly deal with it, but perhaps you are also willing to just raise the Julia compat of this package to 1.6?

**Comment by felipenoris** [comment] 2021-10-21 21:31
Hi @fingolfin !
No problem bumping compat to Julia v1.6.
Thanks for helping with the builders!

**Comment by giordano** [comment] 2021-11-03 22:59
https://github.com/JuliaRegistries/General/pull/47487 is now merged, so MongoC_jll v1.19.1 is available for M1, but as I said above, it segfaults pretty fast

**Comment by felipenoris** [comment] 2021-11-06 19:06
By the latest github CI logs, tests on Linux work just fine.

Julia v1.3 builds with `MongoC_jll v1.16.2+1` and Julia v1.6 builds with `MongoC_jll v1.19.1+0` so there's no need to update Mongoc.jl compat settings.

I had to disable Github CI tests on macOS because MongoDB Github action is not available on that system.

Can anyone with the latest M1 chip confirm that this package works on Julia v1.6 ?

**Comment by giordano** [comment] 2021-11-06 19:09
> Can anyone with the latest M1 chip confirm that the master branch works on Julia v1.6 ?

Julia v1.6 doesn't run on M1, and as I said a couple of time above, tests segfaults almost immediately

**Comment by felipenoris** [comment] 2021-11-06 19:14
@giordano thank you! Can you report here the test logs? In the `runtests.jl` script, please run only `bson_tests.jl` and comment out the rest.

**Comment by giordano** [comment] 2021-11-06 19:24
There isn't really too much:
```console
% julia --project=/tmp bson_tests.jl

signal (11): Segmentation fault: 11
in expression starting at /Users/mose/.julia/packages/Mongoc/gXfqP/test/bson_tests.jl:9
_platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 3203191 (Pool: 3202250; Big: 941); GC: 4
```

**Comment by giordano** [comment] 2021-11-06 19:30
More specifically, the segfault happens on line
https://github.com/felipenoris/Mongoc.jl/blob/812077288784a0d1aed40c2cd41d12c7d9783e31/test/bson_tests.jl#L268

**Comment by felipenoris** [comment] 2021-11-07 00:38
That ccall should reproduce the funcion call example from the docs at 
http://mongoc.org/libbson/current/bson_copy_to_excluding_noinit.html 

One thing that calls my attention is that this function uses a C variadic argument.

Github CI recent tests shows that this function call works fine on non-M1 chips.

**Comment by giordano** [comment] 2021-11-07 01:25
Variadic? It may be similar to https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/497. Where is the source code (not at the computer now)?

**Comment by felipenoris** [comment] 2021-11-07 15:22
@giordano , it's here: https://github.com/felipenoris/Mongoc.jl/blob/f6b7bebf4a0d4e4b16ae62da54507ee48ab7982c/src/c_api.jl#L339 .

**Comment by giordano** [comment] 2021-11-07 16:17
PR opened at #90.

**Closed** 2021-11-07 16:35 UTC
