### ISSUE TITLE
libmongoc not defined

### ISSUE THREAD

**Issue by pptav0** [felipenoris/Mongoc.jl#88] opened 2021-11-02 03:45 UTC
Hi, I'm trying to connect my app to my Mongo DB using Julia. I am finding next error and I've not found any reference yet. I hope you may have some clue

`julia> client = Mongoc.Client()`

```
ERROR: UndefVarError: libmongoc not defined
Stacktrace:
 [1] mongoc_uri_new_with_error(uri_string::String, bson_error_ref::Base.RefValue{Mongoc.BSONError})
   @ Mongoc ~/.julia/packages/Mongoc/gXfqP/src/c_api.jl:351
 [2] URI
   @ ~/.julia/packages/Mongoc/gXfqP/src/types.jl:97 [inlined]
 [3] Mongoc.Client(uri::String)
   @ Mongoc ~/.julia/packages/Mongoc/gXfqP/src/client.jl:27
 [4] client_mongo(config::Dict{String, Any})
   @ Main ~/Codes/Projects/backtest/data/src/utils/database.jl:14
 [5] client_mongo()
   @ Main ~/Codes/Projects/backtest/data/src/utils/database.jl:8
 [6] top-level scope
   @ REPL[23]:1
```

`Pkg.status()`

```
BSON v0.3.4
HTTP v0.8.19
JSON v0.21.2
Mongoc v0.6.2
SimpleWebsockets v0.2.1
StatsBase v0.33.12
WebSockets v1.5.9
```

**Comment by pptav0** [comment] 2021-11-02 04:06
I follow this [instructions](https://stackoverflow.com/questions/65357744/how-to-install-mongodb-on-apple-m1-chip) and then `libmongoc` appears installed  in `/opt/homebrew/lib`, not sure if I need to `symlink` somewhere else so `Pkg.add("Mongoc")` could find it

**Comment by giordano** [comment] 2021-11-03 22:39
@pptav0 when you report this kind of issues please provide as many details as possible, in particular about your operating system.  By the fact you mention homebrew I presume you are on macOS, but what architecture?  Is that ARM or Intel?  In the former case this is a duplicate of #86

**Comment by pptav0** [comment] 2021-11-03 23:14
Thank you for the reply. I checked duplicated issued and it worked. I am adding my system info for further reference.

```
julia> versioninfo()
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

**Closed** 2021-11-03 23:16 UTC
