### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by phinzphinz** [felipenoris/Mongoc.jl#24] opened 2019-03-10 10:24 UTC
When reading from MongoDB I observed a memory overflow and was able to reproduce the problem with the following code sample:

```
using Mongoc

client = Mongoc.Client() # default locahost:27017
db = client["testDB"]
collection=db["testCollection"]
document = Mongoc.BSON()
document["name"] = "Felipe"
document["age"] = 35
document["preferences"] = [ "Music", "Computer", "Photography" ]
# generate some entries
for i = 1:100000
	result = push!(collection, document)
end
# now observe the memory usage (htop) => overflow
for i = 1:10000
	for entry = Mongoc.find(collection)
	end
end
```
It does not help to call `GC.gc()`, the memory usage is incresing with every `Mongoc.find(...)` call. Version information:

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [fbb218c0] BSON v0.2.1
  [336ed68f] CSV v0.4.3
  [54eefc05] Cascadia v0.4.0
  [a93c6f00] DataFrames v0.17.1
  [708ec375] Gumbo v0.5.1
  [cd3eb016] HTTP v0.8.0
  [682c06a0] JSON v0.20.0
  [4fe8b98c] Mongoc v0.1.3
  [39abe10b] MySQL v0.7.0
  [92933f4c] ProgressMeter v0.9.0
  [30578b45] URIParser v0.4.0
  [56ddb016] Logging 
```
My Mongo version:
```
$ mongo --version
MongoDB shell version: 3.2.11
$ mongod --version
db version v3.2.11
git version: 009580ad490190ba33d1c6253ebd8d91808923e4
OpenSSL version: OpenSSL 1.0.2r  26 Feb 2019
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

**Comment by felipenoris** [comment] 2019-03-10 13:53
Hi! I can't reproduce your issue. Did you continue to run the benchmark until you run out of memory?
Can you update to the latest version of Mongoc.jl?

**Comment by felipenoris** [comment] 2019-03-10 13:57
I was able to reproduce this issue.

**Comment by felipenoris** [comment] 2019-03-10 21:27
This should be fixed now. Thanks for reporting this issue!

**Closed by felipenoris** 2019-03-10 21:27 UTC
Labels: bug

**Comment by phinzphinz** [comment] 2019-03-11 08:05
Thank you very much for fixing this!!!
In case it is relevant: I have seen that the new stress test of 76f4b7d uses
```
# generate some entries
for i in 1:100000
    push!(collection, document)
end
```
which is of course not idempotent and would pollute the database with about 10MB on each stress test run. But on the other hand one would lose simplicity if one tried to find a non-existing collection name and dropped it afterwards.

**Comment by felipenoris** [comment] 2019-03-11 12:09
No worries.
